language: rust
rust:
  - stable
cache: cargo
matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - TARGET=x86_64-unknown-linux-gnu
        - PACKAGE=iggy-linux-x86_64.tar.gz
        - CXX=g++-5
    - os: osx
      env:
        - TARGET=x86_64-apple-darwin
        - PACKAGE=iggy-macos-x86_64.tar.gz
        - CXX=clang++
        - CXXFLAGS="-stdlib=libc++ "
        
before_script: 
  - (rustup component add rustfmt || true)
  - (rustup target add $TARGET || true)
  - test "$TRAVIS_OS_NAME" != osx || export MACOSX_DEPLOYMENT_TARGET=10.7
  - export PATH="$PATH:$HOME/.cargo/bin"

script:
  - |
    if [ $TARGET = "x86_64-unknown-linux-gnu" ]; then
      cargo test
    fi
  - cargo build --target $TARGET --verbose --release

before_deploy:
  - tar -czf $PACKAGE -C target/$TARGET/release/ iggy opt_graph

deploy:
  provider: releases
  api_key:
    secure: $IGGY_GITHUB_DEPLOY_OAUTH_TOKEN
  file: ${PACKAGE}
  skip_cleanup: true
  on:
    tags: true
