[package]
name = "iggy"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "Influence graph analysis, consistency check, diagnosis, repair and prediction."
build = "build.rs"
edition = "2018"

[dependencies]
clingo = {path="../clingo-rs" , version = "0.4.0" }
termion = "1"
structopt = "0.2"
failure = "0.1"
failure_derive = "0.1"

[build-dependencies]
peg = { version = "0.5.7" }
