[package]
name = "iggy"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "Influence graph analysis, consistency check, diagnosis, repair and prediction."
build = "build.rs"
edition = "2018"

[dependencies]
clingo = {path="./clingo-rs" }
termion = "1"
structopt = "0.2"

[build-dependencies]
peg = { version = "0.5.7" }
