[package]
name = "iggy"
version = "2.1.1"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "Influence graph analysis, consistency check, diagnosis, repair and prediction."
readme = "README.md"
documentation = "bioasp.github.io/iggy"
repository = "https://github.com/bioasp/iggy"
publish = false
edition = "2018"

[features]
dynamic_linking = ["clingo/dynamic_linking"]

[dependencies]
clingo = { version = "0.6", features = ["derive"] }
structopt = "0.3"
thiserror = "1.0"
anyhow = "1.0"
log = "*"
stderrlog = "0.4"
peg = "0.6"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
