[package]
name = "iggy"
version = "0.1.0"
authors = ["Sven Thiele <sthiele78@gmail.com>"]
description = "Influence graph analysis, consistency check, diagnosis, repair and prediction."

[dependencies]
clingo = "0.3.0"
termion = "1"
clap ="*"
peg-syntax-ext = "0.5.0"